### ISSUE TITLE
invalid secret key when storing sensitive data

### ISSUE THREAD

**Issue by VinozzZ** [getporter/kubernetes-plugins#115] opened 2022-05-25 15:53 UTC
secret key is not compliant with the kubernetes standard,  `a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**Comment by carolynvs** [comment] 2022-05-25 16:06
To be clear, the issue is that porter is calling Create and passing secrets that may not conform to the kubernetes secret naming standard. It is the responsibility of the plugin to detect this condition and create the secret with a name that works.

Thinking about that further, this also means that the Resolve method should perform the same mapping from what porter passed to what it uses to retrieve the secrets. I realize I said the opposite when we were talking in zoom, but that was when we were discussing secrets set by the user in the credential/parameter set. Since porter sends data that is just unusable in k8s, we will need to handle this scenario in both functions.

Please make sure that the test cases include not just uppercase, but unsupported symbols and length. We should probably log a debug message every time we change the source value and it doesn't match the original value passed by porter.

**Comment by carolynvs** [comment] 2022-05-27 00:08
Fixed in #114

**Closed by carolynvs** 2022-05-27 00:08 UTC
Labels: bug
